helmCharts:
  - name: longhorn
    repo: https://charts.longhorn.io
    releaseName: longhorn
    valuesInline:
      defaultSettings:
        defaultDataPath: /store/longhorn
      services:
        ui:
          type: ClusterIP