apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - pvc.yaml
  - ../postgresql

replacements:
  - source:
      kind: Service
      name: homeassistant
      fieldPath: metadata.name
    targets:
      - select:
          kind: Ingress
          name: homeassistant
        fieldPaths:
          - spec.rules.0.http.paths.0.backend.service.name

images:
  - name: homeassistant/home-assistant
    newTag: latest