apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

generatorOptions:
  disableNameSuffixHash: true

secretGenerator:
  - name: cloudflare
    namespace: cert-manager
    files:
      - api-token=secrets/cloudflare-api-token.txt
    type: Opaque
  - name: postgres-env
    namespace: homeassistant
    files:
      - POSTGRES_PASSWORD=secrets/homeassistant-postgres-password.txt
    type: Opaque