apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    email: colewneville2@gmail.com
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - selector:
        dnsZones:
        - coleslab.com
        - local.coleslab.com
        - alexander.coleslab.com
      dns01:
        cloudflare:
          email: colewneville2@gmail.com
          apiTokenSecretRef:
            name: cloudflare
            key: api-token