resources:
  - cluster-issuer-prod.yaml
  - cluster-issuer-staging.yaml

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    releaseName: cert-manager
    valuesInline:
      installCRDs: true
